'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import { ExecSummaryPayload } from '@/lib/executive-summary';

const CACHE_KEY = 'miramar-execsummary-v1';
const MAX_AGE_MS = 30 * 24 * 60 * 60 * 1000; // 30 days — snapshots are infrequent

interface CachedEntry {
  data: ExecSummaryPayload;
  timestamp: number;
}

function getCached(): CachedEntry | null {
  try {
    const raw = localStorage.getItem(CACHE_KEY);
    if (!raw) return null;
    const entry: CachedEntry = JSON.parse(raw);
    if (Date.now() - entry.timestamp > MAX_AGE_MS) {
      localStorage.removeItem(CACHE_KEY);
      return null;
    }
    return entry;
  } catch {
    return null;
  }
}

function setCached(data: ExecSummaryPayload): void {
  try {
    const entry: CachedEntry = { data, timestamp: Date.now() };
    localStorage.setItem(CACHE_KEY, JSON.stringify(entry));
  } catch {
    /* ignore quota / private browsing */
  }
}

export interface UseExecutiveSummaryResult {
  data: ExecSummaryPayload | null;
  loading: boolean;
  error: string | null;
  refetch: () => void;
  isCached: boolean;
  lastFetchedAt: number | null;
  /** True when we tried the static snapshot and it wasn't there. */
  notFound: boolean;
}

/**
 * Reads the executive summary from the static snapshot generated by
 * `npm run snapshot` (committed to public/exec-summary-snapshot.json).
 * On Hobby plan we cannot stream a fresh aggregation in <60s, so the
 * source-of-truth payload is built locally and shipped with each deploy.
 */
export function useExecutiveSummary(refreshTrigger: number): UseExecutiveSummaryResult {
  const [data, setData] = useState<ExecSummaryPayload | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isCached, setIsCached] = useState(false);
  const [lastFetchedAt, setLastFetchedAt] = useState<number | null>(null);
  const [notFound, setNotFound] = useState(false);
  const mountedRef = useRef(true);

  const fetchSnapshot = useCallback(async (force: boolean) => {
    setLoading(true);
    setError(null);
    setNotFound(false);
    try {
      const url = `/exec-summary-snapshot.json${force ? `?t=${Date.now()}` : ''}`;
      const res = await fetch(url, { cache: force ? 'no-store' : 'default' });
      if (!mountedRef.current) return;
      if (res.status === 404) {
        setNotFound(true);
        setLoading(false);
        return;
      }
      if (!res.ok) throw new Error(`Failed to load snapshot: HTTP ${res.status}`);
      const payload: ExecSummaryPayload = await res.json();
      setData(payload);
      setIsCached(false);
      setLastFetchedAt(Date.now());
      setCached(payload);
      setLoading(false);
    } catch (e: any) {
      if (!mountedRef.current) return;
      setError(e?.message || 'Failed to load snapshot');
      setLoading(false);
    }
  }, []);

  // Hydrate from localStorage immediately, then fetch the static file fresh.
  useEffect(() => {
    mountedRef.current = true;
    const cached = getCached();
    if (cached) {
      setData(cached.data);
      setIsCached(true);
      setLastFetchedAt(cached.timestamp);
    }
    // Always try the network too — if the deployed snapshot is newer, take it.
    fetchSnapshot(false);
    return () => {
      mountedRef.current = false;
    };
  }, [fetchSnapshot]);

  // Manual refresh — bust the cache and re-fetch
  useEffect(() => {
    if (refreshTrigger === 0) return;
    fetchSnapshot(true);
  }, [refreshTrigger, fetchSnapshot]);

  const refetch = useCallback(() => fetchSnapshot(true), [fetchSnapshot]);

  return { data, loading, error, refetch, isCached, lastFetchedAt, notFound };
}
